// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using makeITeasy.PerformanceReview.Infrastructure;
using makeITeasy.PerformanceReview.Infrastructure.Data;
using makeITeasy.PerformanceReview.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace makeITeasy.PerformanceReview.Infrastructure.Data.Configurations
{
    public partial class EvaluationConfiguration : IEntityTypeConfiguration<Evaluation>
    {
        public void Configure(EntityTypeBuilder<Evaluation> entity)
        {
            entity.ToTable("Evaluation");

            entity.Property(e => e.ManagerIdentityId).HasMaxLength(450);

            entity.Property(e => e.UserIdentityId).HasMaxLength(450);

            entity.HasOne(d => d.Form)
                .WithMany(p => p.Evaluations)
                .HasForeignKey(d => d.FormId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Evaluation_ToForm");

            entity.HasOne(d => d.UserIdentity)
                .WithMany(p => p.Evaluations)
                .HasForeignKey(d => d.UserIdentityId)
                .HasConstraintName("FK_Evaluation_ToEmployee");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Evaluation> entity);
    }
}
