// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using makeITeasy.PerformanceReview.Infrastructure;
using makeITeasy.PerformanceReview.Infrastructure.Data;
using makeITeasy.PerformanceReview.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace makeITeasy.PerformanceReview.Infrastructure.Data.Configurations
{
    public partial class FormItemConfiguration : IEntityTypeConfiguration<FormItem>
    {
        public void Configure(EntityTypeBuilder<FormItem> entity)
        {
            entity.ToTable("FormItem", "perfReview");

            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(512)
                .IsUnicode(false);

            entity.Property(e => e.FormItemType).HasDefaultValueSql("0");

            entity.HasOne(d => d.Form)
                .WithMany(p => p.FormItems)
                .HasForeignKey(d => d.FormId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PerformanceReviewQuestion_ToPerformanceReview");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FormItem> entity);
    }
}
