// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using makeITeasy.PerformanceReview.Infrastructure;
using makeITeasy.PerformanceReview.Infrastructure.Data;
using makeITeasy.PerformanceReview.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace makeITeasy.PerformanceReview.Infrastructure.Data.Configurations
{
    public partial class PerformanceReviewEvaluationItemConfiguration : IEntityTypeConfiguration<PerformanceReviewEvaluationItem>
    {
        public void Configure(EntityTypeBuilder<PerformanceReviewEvaluationItem> entity)
        {
            entity.ToTable("PerformanceReviewEvaluationItem");

            entity.HasOne(d => d.PerformanceReviewEvalution)
                .WithMany(p => p.PerformanceReviewEvaluationItems)
                .HasForeignKey(d => d.PerformanceReviewEvalutionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PerformanceReviewEvaluationItem_ToPerformanceReviewEvalution");

            entity.HasOne(d => d.PerformanceReviewItem)
                .WithMany(p => p.PerformanceReviewEvaluationItems)
                .HasForeignKey(d => d.PerformanceReviewItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PerformanceReviewEvaluationItem_ToPerformanceReviewItem");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PerformanceReviewEvaluationItem> entity);
    }
}
